version: "3.8"
services:
  app:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  game_service:
    container_name: game_service
    build:
      context: ./backend/game_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./backend/game_service:/usr/src/app/game_service/src
    depends_on:
      - rabbitmq
  rule_service:
    container_name: rule_service
    build:
      context: ./backend/rule_service
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8002"
    restart: on-failure
    volumes:
      - ./backend/rule_service:/usr/src/app/rule_service/src
    depends_on:
      - rabbitmq
  player_service:
    container_name: player_service
    build:
      context: ./backend/player_service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    restart: on-failure
    volumes:
      - ./backend/player_service:/usr/src/app/player_service/src
    depends_on:
      - rabbitmq
  authentication_service:
    container_name: authentication_service
    build:
      context: ./backend/authentication_service
      dockerfile: Dockerfile.dev
    ports:
      - "8003:8003"
    restart: on-failure
    volumes:
      - ./backend/authentication_service:/usr/src/app/authentication_service/src
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
volumes:
  mongodb:
